/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jframe;

import javax.swing.JOptionPane;

/**
 *
 * @author fazli
 */
public class Entrance extends javax.swing.JFrame {

    /**
     * Creates new form Entrance
     */
    public Entrance() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGroundPanel = new javax.swing.JPanel();
        LoadingLabel = new javax.swing.JLabel();
        LoadingValue = new javax.swing.JLabel();
        LoadingLa = new javax.swing.JLabel();
        LoadingBar = new javax.swing.JProgressBar();
        BackgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackGroundPanel.setBackground(new java.awt.Color(255, 255, 255));
        BackGroundPanel.setMinimumSize(new java.awt.Dimension(790, 560));
        BackGroundPanel.setPreferredSize(new java.awt.Dimension(800, 540));
        BackGroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoadingLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LoadingLabel.setText("Loading...");
        BackGroundPanel.add(LoadingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 800, 400, 40));

        LoadingValue.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        LoadingValue.setText("0 %");
        BackGroundPanel.add(LoadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 800, -1, 40));

        LoadingLa.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        LoadingLa.setForeground(new java.awt.Color(102, 0, 153));
        LoadingLa.setText("BOOKAHOLIC");
        BackGroundPanel.add(LoadingLa, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 40, 410, -1));
        BackGroundPanel.add(LoadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 850, 1300, 50));

        BackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/signup-library-icon.png"))); // NOI18N
        BackGroundPanel.add(BackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 790, 730));

        getContentPane().add(BackGroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1030));

        setSize(new java.awt.Dimension(1917, 1027));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entrance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entrance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entrance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entrance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        Entrance ent = new Entrance();
        ent.setVisible(true);
        
        
        try {
            for (int i = 0; i <= 100; i++) {
                Thread.sleep(100);
                ent.LoadingValue.setText(i +"%");
                if(i==10){
                     ent.LoadingLabel.setText("Turning On Modules...");
                }
                if(i==20){
                    ent.LoadingLabel.setText("Loading Modules...");
                }
                if(i==50){
                    ent.LoadingLabel.setText("Connecting to Database...");
                }
                if(i==70){
                    ent.LoadingLabel.setText("Connected Successfully !");
                }
                if(i==80){
                    ent.LoadingLabel.setText("Launching Application...");
                }
                
                   ent.LoadingBar.setValue(i);
           
            }
              SignupPage page=new SignupPage();
             page.setVisible(true);
           ent.setVisible(false);
        } catch (Exception e) {
           
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGroundPanel;
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JProgressBar LoadingBar;
    private javax.swing.JLabel LoadingLa;
    private javax.swing.JLabel LoadingLabel;
    private javax.swing.JLabel LoadingValue;
    // End of variables declaration//GEN-END:variables
}
